#nodb check
name: Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 19.x, 20.x, 21.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: ./packages/actions/pnpm
        
      - name: Run tests and collect coverage | nodb
        run: |
          cd packages/discord-afk-js_nodb
          pnpm i && pnpm run test

      # - name: Run tests and collect coverage | db
      #   run: |
      #     cd packages/discord-afk-js_db
      #     pnpm i && pnpm run test

      # Copy and paste the codecov/test-results-action here
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: github.repository_owner == 'sitcommunity'
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
